name: CI Develop
on:
  push:
    branches:
      - develop
  workflow_dispatch:  # Permet de lancer manuellement via l'IHM
  
env: 
  AZURE_WEBAPP_NAME: 'globomantics-web-game-touig'   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '9.0'
  
jobs:
  verify:
    name: Vérification initiale
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log environnement
        run: env

      - name: Vérification de l'intégrité du projet
        run: echo "Vérification OK"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Log environment
        run: env
